# Generated by Django 4.2 on 2023-05-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('logo', models.BinaryField(null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('postal_code', models.PositiveSmallIntegerField(null=True)),
                ('street', models.CharField(max_length=45, null=True)),
                ('street_number', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('model_number', models.PositiveSmallIntegerField(null=True)),
                ('manufacturer', models.CharField(max_length=30, null=True)),
                ('agency_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('boarding_pass_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('gate', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=3, null=True)),
                ('flight_id', models.PositiveIntegerField()),
                ('ticket_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('aircraft_id', models.PositiveIntegerField()),
                ('origin', models.PositiveIntegerField()),
                ('destination_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('passenger_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PilotFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_id', models.PositiveIntegerField()),
                ('flight_id', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('pilot_id', 'flight_id')},
            },
        ),
    ]
