# Generated by Django 4.2 on 2023-06-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the agency name', max_length=45, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(null=True, upload_to='agency_logos', verbose_name='Logo')),
                ('city', models.CharField(help_text='Enter the city', max_length=20, null=True, verbose_name='City')),
                ('postal_code', models.PositiveSmallIntegerField(help_text='Enter the postal code', null=True, verbose_name='Postal Code')),
                ('street', models.CharField(help_text='Enter the street', max_length=45, null=True, verbose_name='Street')),
                ('street_number', models.CharField(help_text='Enter the street number', max_length=45, null=True, verbose_name='Street Number')),
                ('email', models.EmailField(help_text='Enter the email', max_length=100, null=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Enter the phone number', max_length=45, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.PositiveSmallIntegerField(help_text='Enter the model number', null=True, verbose_name='Model Number')),
                ('manufacturer', models.CharField(help_text='Enter the manufacturer', max_length=30, null=True, verbose_name='Manufacturer')),
                ('agency', models.ForeignKey(help_text='Select the agency', on_delete=django.db.models.deletion.CASCADE, to='myapp.agency', verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircrafts',
                'ordering': ['manufacturer', 'model_number'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the airport name', max_length=45, null=True, verbose_name='Name')),
                ('city', models.CharField(help_text='Enter the city', max_length=30, null=True, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(help_text='Enter the departure date', verbose_name='Departure Date')),
                ('arrival_date', models.DateTimeField(help_text='Enter the arrival date', verbose_name='Arrival Date')),
                ('aircraft', models.ForeignKey(help_text='Select the aircraft', on_delete=django.db.models.deletion.CASCADE, to='myapp.aircraft', verbose_name='Aircraft')),
                ('destination', models.ForeignKey(help_text='Select the destination airport', on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='myapp.airport', verbose_name='Destination')),
                ('origin', models.ForeignKey(help_text='Select the origin airport', on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='myapp.airport', verbose_name='Origin')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=45, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=45, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Enter the email', max_length=45, null=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Enter the phone number', max_length=45, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=45, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=45, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Pilot',
                'verbose_name_plural': 'Pilots',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price', max_digits=10, null=True, verbose_name='Price')),
                ('passenger', models.ForeignKey(help_text='Select the passenger', on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger', verbose_name='Passenger')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.PositiveSmallIntegerField(help_text='Enter the gate number', verbose_name='Gate')),
                ('status', models.CharField(help_text='Enter the status', max_length=3, null=True, verbose_name='Status')),
                ('flight', models.ForeignKey(help_text='Select the flight', on_delete=django.db.models.deletion.CASCADE, to='myapp.flight', verbose_name='Flight')),
                ('ticket', models.ForeignKey(help_text='Select the ticket', on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Boarding Pass',
                'verbose_name_plural': 'Boarding Passes',
                'ordering': ['gate'],
            },
        ),
        migrations.CreateModel(
            name='PilotFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(help_text='Select the flight', on_delete=django.db.models.deletion.CASCADE, to='myapp.flight', verbose_name='Flight')),
                ('pilot', models.ForeignKey(help_text='Select the pilot', on_delete=django.db.models.deletion.CASCADE, to='myapp.pilot', verbose_name='Pilot')),
            ],
            options={
                'verbose_name': 'Pilot Flight',
                'verbose_name_plural': 'Pilot Flights',
                'unique_together': {('pilot', 'flight')},
            },
        ),
    ]
