# Generated by Django 4.2 on 2023-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['manufacturer', 'model_number'], 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircrafts'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name'], 'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='boardingpass',
            options={'ordering': ['gate'], 'verbose_name': 'Boarding Pass', 'verbose_name_plural': 'Boarding Passes'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_date'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
        migrations.AlterModelOptions(
            name='pilot',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Pilot', 'verbose_name_plural': 'Pilots'},
        ),
        migrations.AlterModelOptions(
            name='pilotflight',
            options={'verbose_name': 'Pilot Flight', 'verbose_name_plural': 'Pilot Flights'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['price'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.PositiveIntegerField(help_text='Enter the agency ID', primary_key=True, serialize=False, verbose_name='Agency ID'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(help_text='Enter the city', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(help_text='Enter the email', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.BinaryField(null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(help_text='Enter the agency name', max_length=45, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(help_text='Enter the phone number', max_length=45, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='postal_code',
            field=models.PositiveSmallIntegerField(help_text='Enter the postal code', null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='street',
            field=models.CharField(help_text='Enter the street', max_length=45, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='street_number',
            field=models.CharField(help_text='Enter the street number', max_length=45, null=True, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='agency_id',
            field=models.PositiveIntegerField(help_text='Enter the agency ID', verbose_name='Agency ID'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_id',
            field=models.PositiveIntegerField(help_text='Enter the aircraft ID', primary_key=True, serialize=False, verbose_name='Aircraft ID'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.CharField(help_text='Enter the manufacturer', max_length=30, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model_number',
            field=models.PositiveSmallIntegerField(help_text='Enter the model number', null=True, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_id',
            field=models.PositiveIntegerField(help_text='Enter the airport ID', primary_key=True, serialize=False, verbose_name='Airport ID'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(help_text='Enter the city', max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(help_text='Enter the airport name', max_length=45, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='boarding_pass_id',
            field=models.PositiveIntegerField(help_text='Enter the boarding pass ID', primary_key=True, serialize=False, verbose_name='Boarding Pass ID'),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='flight_id',
            field=models.PositiveIntegerField(help_text='Enter the flight ID', verbose_name='Flight ID'),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='gate',
            field=models.PositiveSmallIntegerField(help_text='Enter the gate number', verbose_name='Gate'),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='status',
            field=models.CharField(help_text='Enter the status', max_length=3, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='ticket_id',
            field=models.PositiveIntegerField(help_text='Enter the ticket ID', verbose_name='Ticket ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft_id',
            field=models.PositiveIntegerField(help_text='Enter the aircraft ID', verbose_name='Aircraft ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateTimeField(help_text='Enter the arrival date', verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(help_text='Enter the departure date', verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_id',
            field=models.PositiveIntegerField(help_text='Enter the destination ID', verbose_name='Destination ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.PositiveIntegerField(help_text='Enter the flight ID', primary_key=True, serialize=False, verbose_name='Flight ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.PositiveIntegerField(help_text='Enter the origin', verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(help_text='Enter the email', max_length=45, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(help_text='Enter the first name', max_length=45, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(help_text='Enter the last name', max_length=45, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.PositiveIntegerField(help_text='Enter the passenger ID', primary_key=True, serialize=False, verbose_name='Passenger ID'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(help_text='Enter the phone number', max_length=45, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='first_name',
            field=models.CharField(help_text='Enter the first name', max_length=45, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='last_name',
            field=models.CharField(help_text='Enter the last name', max_length=45, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='pilot_id',
            field=models.PositiveIntegerField(help_text='Enter the pilot ID', primary_key=True, serialize=False, verbose_name='Pilot ID'),
        ),
        migrations.AlterField(
            model_name='pilotflight',
            name='flight_id',
            field=models.PositiveIntegerField(help_text='Enter the flight ID', verbose_name='Flight ID'),
        ),
        migrations.AlterField(
            model_name='pilotflight',
            name='pilot_id',
            field=models.PositiveIntegerField(help_text='Enter the pilot ID', verbose_name='Pilot ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_id',
            field=models.PositiveIntegerField(help_text='Enter the passenger ID', verbose_name='Passenger ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.PositiveIntegerField(help_text='Enter the ticket ID', primary_key=True, serialize=False, verbose_name='Ticket ID'),
        ),
    ]
